backend:
  name: github
  repo: oacedamy-droid/oacedamy.io
  branch: main

media_folder: "img"          # you already have an img folder
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
